truecover:
    backend:
        database:
            username: ENC[AES256_GCM,data:XLANLTAOIaDm,iv:uWoxyS4kTzAHgSuLUx8YKEDTQSEdblGTxjJ1g/KEF0I=,tag:O8iBMYtSxyTIp0bAcWtb2Q==,type:str]
            password: ENC[AES256_GCM,data:7F70eMubE9ntWi3vXA9U2orUyiCGy9FDyxab2LuUbUc=,iv:P4Xw6fdPfPGghoN0Io7IVmdwOy4sAig0FWBwCepDWr0=,tag:FyhJ0Vk+6V2qZUa6uh/EMQ==,type:str]
        clerk:
            secretKey: ENC[AES256_GCM,data:RkAAA8222pI6QJPyRVkhTZL0LL2HaL7GYgo67uASy0Q+PR+xhw==,iv:H+nwD6iPLPNbaFg7WavInvu4Bvfh0sMd8/JPF45lPfc=,tag:nnByXu5hq+T4anIC0rbOrw==,type:str]
    frontend:
        mapbox:
            token: ENC[AES256_GCM,data:M2U5RwlegV9zgoK2DWemri82l5U28S4EF4+9KMvzNSSWBdoZXaHJ/eSeGLQLLLHYLLCixkWhvWNMKCkKIjpSm4UdABoZ8P1/ZZ85sbtdT1uj7aCZ,iv:mQDSIGBMgzx4KnFL/7Y0iFak1suge15odKeJktImwec=,tag:z59srkfTftTjemDRAKZJ7g==,type:str]
        clerk:
            publishableKey: ENC[AES256_GCM,data:nnhhvysIt35kpb8GJMh7AEZKAinwJTEvFkFCBDrGl8y8gdMfMw==,iv:Vmxl6uIpePRO/lcCbQoRw5tqvORJvD9hIFueCYX3Oeg=,tag:jbIr5s6sffRk9zGKc1/Idg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:447036922786:key/2c8d9ad7-865c-475f-95db-cda194659aec
          created_at: "2020-12-04T16:27:08Z"
          enc: AQICAHgH7UzpLScdMM9I4zircxhweG7VauxU4ybl0yxH8BYTMwG0qfkIOg75AlwBiCh0hwGJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMl4nSh2Kx9vm34VMsAgEQgDvUirvz5ubml7kigAPUZPK/by4P3EbRqCVSp4fy1Vbl4GziK0iLs9zSZF1e9JfrhWKV1iEIHPcy+EaYIQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-26T13:35:08Z"
    mac: ENC[AES256_GCM,data:+NfFOn2YXbAeIVN0FTvJlkgWGjGlGU84LOvmOcvdsoQRAW+zMHSDbRmDSDsXNDo5MIZPqbqeJmN+loBVUoJv0LYME5X66ZT5ZZmGzVX81xK6hrMkRSaesUPectVAyd7QzLDZXlXaaFPPBP6vLDUKkPZZk5D4jQGQBVQ1Xc6+uyE=,iv:8AknU1W0EJcSxhs6jfM2UVvg4UBAC4Rk01TMShiaTLo=,tag:mqOfutTvZ5jVisaG5Xxj3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
